### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by matthuisman** [Conceiva/MezzmoKodiPlugin#10]
Really cool addon! 

Its a shame Mezzmo is windows only.

My biggest issue with my current setup at home is the shared MySQL over network is slow.
I was thinking of writing an addon that would sync shared MySQL to local kodi db.
So all clients use a local db for better speed.

How hard is maintaining the sync in your addon?

Also, your search  - does that search Mezzmo or use kodis api to search kodi local db?

**Comment by jbinkley60** [comment]
Sorry for the delay getting back to you.  I've been traveling.  Thanks for the compliment.

Yes, Mezzmo is limited to Windows but it can run as a Windows VM under Linux or using WINE.  Running on Windows has some advantages as far as the GUI and easier connectivity to SMB shares (vs. what I see folks go through with Kodi SMB shares).  Certainly a good Linux admin can negate these things.  Some of the other drive tools like  [expanding capacity](https://github.com/Conceiva/MezzmoKodiPlugin/wiki/How-it-works-%3F#adding-capacity) and [moving media](https://github.com/Conceiva/MezzmoKodiPlugin/wiki/How-it-works-%3F#moving-media-locations) work very well under windows.  

Maintaining the addon hasn't been too difficult.  It does as you have determined, sync Mezzmo to Kodi.  It also does a few other things like detecting duplicates, provides for an on demand full library rebuild and does a daily full rebuild.  As far as addng other content, that is easiest by adding it to Mezzmo and then let the addon sync it to Kodi.  Mezzmo will handle [automatically finding](https://github.com/Conceiva/MezzmoKodiPlugin/wiki/Managing-Your-Library#automatic-discovery) new content based upon your setting and will scrape the content metadata or read the NFO file (depending upon your setup).  I do this with my OTA content.  Mezzmo checks every 2 minutes.  

The search is against Mezzmo's database, which allows a wide range of[ search settings](https://github.com/Conceiva/MezzmoKodiPlugin/wiki/Searching-Your-Library).  If Mezzmo is discovering new content then the search is real time as soon as it is added to the library.  

My goal is to centrally manage Kodi via Mezzmo and not manage the clients.  If all content goes through Mezzmo then t can leverage all of the tools in Mezzmo and the addon.  

I hope this helps.  Happy to chat further.

**Comment by jbinkley60** [comment]
Questions answered.  No further inquiries.
