### ISSUE TITLE
IMDB Field blank

### ISSUE THREAD

**Issue by Nova77x** [Conceiva/MezzmoKodiPlugin#4]
xbmc.getInfoLabel('VideoPlayer.IMDBNumber') returns blank. The rest of the fields appear to be filled correctly.

**Comment by jbinkley60** [comment]
Correct.  Right now that data isn't populated in the Kodi database but is available on the Mezzmo server GUI.  I am curious as to the use case for this ?  A lot more metadata is being added with version 1.1.5.5 and 2.1.5.5 but the IMDB info currently isn't planned.  I've looked at the cod involved and it doesn't look too bad.  I'll see if I can add it to the next release.  If not, for sure the one after.

**Comment by jbinkley60** [comment]
Populating IMDB information into the Kodi DB from Mezmo has been committed to the upcoming 1.1.5.5 and 2.1.5.5 releases of the addon.  These versions should be released this week by May 27th , unless a new bug is found.

**Comment by jbinkley60** [comment]
Versions 1.1.5.5 and 2.1.5.5 have been released.
